validations.go

It does not make sense to read symbol table for older Go versions, since we will skip the checks anyway.
Move the version check to be the first one.

perf: validateGoSymbols: skip early

---

node_scan.go

Currently, the node scan error report has the full file name on the host:
```
./check-payload scan node --root /some/very/long/path
.......
---- Failure Report
+----------------+--------------------------------------+------------------------------------+
| PATH           | STATUS                               | FROM                               |
+----------------+--------------------------------------+------------------------------------+
| /sbin/ldconfig | executable is not dynamically linked | /some/very/long/path/sbin/ldconfig |
+----------------+--------------------------------------+------------------------------------+
```
I think it makes more sense to use rpm name as a tag, otherwise FROM does not add any new information (it's --root argument + PATH).
With this change:
``` …
```

fix: use rpm name as tag in node scan

---

main.go
printer.go
scan.go
types.go
types_scan_result.go
validations.go

Changes strictfipsruntime flag to be a warning and adds warning error support to the application.
Additionally adds `--fail-on-warnings` flag to preserve warnings as errors.

add warning support and --fail-on-warnings flag

---

dist/releases/4.9/config.toml
main.go

Return an error otherwise.
This actually helped to find an error in 4.9 config (which is fixed). Before the fix, the error looked like this:
> Error: unknown keys in config: [node."podman-catatonit-3.2.3-0.12.module+el8.4.0+14908+81312c48.x86_64".filter_images]
_this used to be part of #33_

feat: ensure the config is fully parsed

---

go.mod
go.sum
internal/types/types_config.go

Some fields are now missing from the log. Generally, it is not very realistic to keep the Log function in sync with the configuration.
The solution is to use %+v which will print all the fields.
While at it, do not print git commit since we already do better than that in main.go (right after calling config.Log()).
(_this used to be a part of #33_)

fix: log the entire configuration

---

internal/validations/validations.go

See individual commits.
(_this used to be a part of #33_)

Minor scanBinary cleanups

---

internal/golang/goscan.go
internal/validations/validations.go

1. Document that we are looking for ANY of the expected symbols.
2. Simplify the code.
3. Return bool instead of an error. This avoid wrapping errors.
_this used to be part of #33_

ExpectedSyms: document, refactor, return bool

---

internal/scan/printer.go

1. Use `ToSlice` only once.
2. Use `%q` where appropriate
3. Use `fmt.Println` where appropriate.

fix: simplify displayExceptions

---

internal/validations/validations.go
internal/validations/validations_test.go

Also
- add some benchmarks;
- use substring matching instead of mapset for checking go build tags.
See individual commits for details.

optimize using regular expressions

---

dist/releases/4.10/config.toml
dist/releases/4.11/config.toml
dist/releases/4.12/config.toml
dist/releases/4.13/config.toml
dist/releases/4.9/config.toml
internal/rpm/rpm.go
internal/scan/node_scan.go
internal/types/types.go
internal/types/types_config.go

This is done in preparation to support per-rpm exclusions in payload scan.
Please see individual commit messages for details.
The only notable changes are:
- `node.` is now `rpm.` in configs;
- only the rpm name is used in configs.

rpm-related refactoring and cleanups

---

dist/releases/4.10/config.toml
dist/releases/4.11/config.toml
dist/releases/4.12/config.toml
dist/releases/4.13/config.toml

chore: [CRW-4582](https://issues.redhat.com//browse/CRW-4582) exclude /usr/libexec/catatonit/catatonit in payload.devspaces-udi-rhel8-container as it's already excluded in root config.toml
Signed-off-by: Nick Boldt <nboldt@redhat.com>

chore: CRW-4582 exclude /usr/libexec/catatonit/catatonit in payload.devspaces-udi-rhel8-container as it's already excluded in root config.toml

---

internal/rpm/rpm.go
internal/scan/node_scan.go
internal/scan/printer.go
internal/scan/scan.go
internal/types/types.go
internal/types/types_scan_result.go
internal/validations/validations.go

This adds rpm name support to payload scan, so we can see which rpm the failed file belongs to, as well as use per-rpm exclusions (previously only available to node scans) for payload scans.
TODO: convert configs to mostly contain rpm-based exclusions (NOT in this PR).

Rpm to scan

---

dist/releases/4.9/config.toml

Commit 33b5277ec32d resulted in two rpm.cri-o sections.
Remove the duplicate (which results in a panic -- we need to add a CI job to prevent this).

hotfix: fix 4.9 config

---

internal/scan/node_scan.go
internal/scan/scan.go

Such files are most probably not binaries, or they are binaries that
can't be executed (until `x` bit is set, that is).
This helps to skip calling `isElfExe` for most libraries.
Shows a noticeable improvement on my machine.

perf: skip all files with no x bit set

---

internal/rpm/rpm.go
internal/scan/node_scan.go

This fixes three issues with node scan, two of which prevented node scans from working.
The first one was introduced by #75 and broke all node scans.
The second one was there from the beginning and broke some node scans.
The last issue was not reporting errors from `rpm -qa`.
See individual commits for more details.
Tested to fix the issue of not being able to use node scan.

Node scan hotfixes

---

config.toml
dist/releases/4.13/config.toml
internal/types/types.go
internal/types/types_config.go

Note that the exceptions printer won't print those.
See the commit for usage examples.

feat: add dirs to per-error exclusion lists

---

dist/releases/config_test.go
dist/releases/embeds.go

The test checks that
- configs can be parsed
- there are no unknown/unparsed parts
This ensures there are no runtime errors due to bad embedded configs.

test: check that embedded configs are sane

---

internal/validations/validations.go
main.go

~~_(based on and currently includes #87; draft until that one is merged; if you want to review, see the last commit only)_~~
Instead of running `file`, use debug/elf (which we already use anyway)
to check for static binaries, which is much faster.

Use debug/elf to check for dynamic binaries

---

config.toml

In some old distros, it's /sbin/ldconfig not /usr/sbin/ldconfig, so we need to exclude both.
Found using node scan using check-payload node scan -V 4.9 --root \
$(podman image mount quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:91e37c277d80facba198afcbb05c06c0f27b6f9c7bb4f2dd64cf12e331a0dc58)

chore: add /sbin/ldconfig to ignore

---

CHANGELOG.md
internal/scan/node_scan.go
internal/scan/scan.go
internal/types/types.go
main.go

See individual commits for details.
Surprisingly, `scan node --walk-scan` is much faster than the default mode.
Fixes: #87

OCPNODE-1743: Implement `--rpm-scan` for payload/image, `--walk-scan` for node scans

---

dist/releases/4.13/config.toml

This is already excluded by main config.toml:
> [[rpm.containernetworking-plugins.ignore]]
> error = "ErrGoMissingTag"
> dirs = [ "/usr/libexec/cni" ]

chore: remove a dup from 4.13 config

---

dist/releases/config_test.go
internal/types/types_config_file.go

With this fix, the config validation now properly detects the dupe that was
fixed earlier in commit a8c7f00 / PR #106 (which it failed to detect before).
With that commit reverted, the failure looks like this:
> === RUN   TestConfigs
>     config_test.go:47: main+4.13 combined config failed validation: errors: <nil>; warnings: config entry [[rpm.containernetworking-plugins.ignore]].error=ErrGoMissingTag.files contains a redundant path "/usr/libexec/cni/dummy", overlapped by "/usr/libexec/cni"
> --- FAIL: TestConfigs (0.00s)

Config validation fixups

---

config.toml

Joe Lanford says:
> We copy this binary into a scratch image, so it needs to be statically
> compiled. It does not do any crypto.
Since this binary will also be in a future releases, place it in a global config.
Tested with:
```console
$ ./check-payload scan payload -u registry.ci.openshift.org/ocp/release:4.14.0-0.nightly-2023-09-21-002530 -V 4.14
...
---- Successful run
```

config.toml: add exception for rukpak

---

config.toml

In 4.15+, OLM will not require that users provide an `opm` binary with their index image. In cases where they do not, OLM simply copies the catalog data from their index image and uses it directly. In order to copy this data, we do not want to assume anything about the image that contains the content we need to copy, so we statically compile a utility that helps us copy the data around, instead of assuming the image has `sh` or `cp`.

exclude a statically-compiled utility for OLM

---

.gitignore
README.md
config.toml
dist/releases/embeds.go
dist/releases/java/FIPS.java
internal/podman/podman.go
internal/scan/scan.go
internal/types/types.go
internal/validations/validations.go
main.go

```bash
% sudo ./check-payload scan java -h               
Usage:
check-payload scan java-image [image pull spec] [flags]
Aliases:
java-image, java
Flags:
--disabled-algorithms strings   additional algorithms that java should be disabling in FIPS mode
-h, --help                          help for java-image
--rpm-scan                      use RPM scan (same as during node scan)
--spec string                   java payload url
```
Requirements to run -
- FIPS enabled host. This is required in order to verify java is properly configured for FIPS at runtime. 
- Scans images w/ jdk 1.8+ installed
example printer outputs -
```
---- Failure Report
+----------------------------------------------+--------------------------------------------+
| STATUS                                       | IMAGE …
```

add Java / JDK image scan option

---

Dockerfile

Add opm so that we can run the operator index image check in the container.
Doc for opm installation: https://docs.openshift.com/container-platform/4.14/cli_reference/opm/cli-opm-install.html

Add opm so that we can run the operator index image check in the container

---

config.toml
dist/releases/4.14/config.toml
internal/types/error_map.go
internal/types/errors.go
internal/validations/validations.go

Check for goexperimental with golang >= 1.18.
Fixed #81

OCPBUGS-24612: check for goexperimental >= 1.18

---

config.toml

It was probably removed by accident via https://github.com/openshift/check-payload/commit/99877fc3a64433482777306442c600e5802c51d7

Adding /usr/bin/tini-static back to the ignore list

---

dist/releases/4.16/config.toml

https://github.com/openshift/bond-cni/blob/release-4.16/Dockerfile.openshift copies RHEL 8 binary to RHEL 9 base

Add exception for bond cni RHEL 8 binary in RHEL 9 base

---

dist/releases/4.15/config.toml

Follows https://github.com/openshift/check-payload/pull/168
4.15 scan result against payload `quay.io/openshift-release-dev/ocp-release:4.15.8-x86_64`
```
| OPERATOR NAME              | TAG NAME  | EXECUTABLE NAME                  | STATUS                                                                            | IMAGE                                                                                                                  |
+----------------------------+-----------+----------------------------------+-----------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------+
| oc-mirror-plugin-container | oc-mirror | /usr/bin/oc-mirror.rhel8         | …
```

update 4.15 ignores

---

README.md

A recent change refactored the bundle directory naming and structure, but we're still using the old names in the README.
https://github.com/openshift/check-payload/commit/d21f5cdc51824f5c270bd8c0ce8d8f5af679161b
This commit updates the doc to align with what's in tree.

Update docs to reference correct bundle directory

---

dist/releases/4.15/config.toml
dist/releases/4.16/config.toml

VolSync packages diskrsync which uses  x/crypto/blake2b for non-cryptographic use (local hashing).
It then never calls out to code to do any network transfers (will exec the ssh executable on the image itself for transferring files), so also does not build dynamically.
Looking to exclude disksync from the check-payload scanner for OpenShift v4.15 and up.

volsync-container exception for diskrsync binary

---

dist/releases/4.11/config.toml

**Build**: openshift-enterprise-operator-sdk-container-v4.11.0-202405110035.p0.g802a594.assembly.stream.el8
**Pullspec**: registry-proxy.engineering.redhat.com/rh-osbs/openshift-ose-operator-sdk@sha256:99e4e4b5f6a1918c09ac909b200f5547f62be9d5e52400e60097d7cce5b843d0
**Dockerfile**: https://github.com/openshift/ocp-release-operator-sdk/blob/release-4.11/release/sdk/Dockerfile

Update 4.11 exclude

---

dist/releases/4.15/config.toml

Dockerfile: https://github.com/openshift/sriov-cni/blob/release-4.15/Dockerfile.rhel
Slack [thread](https://redhat-internal.slack.com/archives/CB95J6R4N/p1715889366059319)

[4.15] exclude sriov-cni-container ErrLibcryptoSoMissing

---

config.toml

The single "[" resulted in ignoring the following lines in the
config file.
In addition, payload.operator-lifecycle-manager-container and
payload.ose-olm-rukpak-container are missing the error to
mask.

Fix braces

---

Dockerfile
Dockerfile.upstream

Adds skopeo and umoci binaries to the check-payload image (useful when using `scan local`).
xref: https://redhat-internal.slack.com/archives/C05U13J3LLS/p1716476010936559?thread_ts=1715954957.336589&cid=C05U13J3LLS

Add skopeo and umoci to CI image

---

internal/scan/scan_test.go
internal/types/types.go

The `NewDefaultConfig` method has a few issues:
- its name is misleading (it does not create a new object);
- it is only used in tests (and thus do not belong to non-test codebase);
- it has quite a few inits that are redundant.
Remove it, and add a simple init right to the test case. We can move it
out to a separate function in test later if need arises.

int/types: rm NewDefaultConfig

---

internal/validations/validations.go

Original PR[1] added the go 1.22 version check wrongly, this patch fixes it.
[1] https://github.com/openshift/check-payload/pull/196
Related-Issue: [CMP-2633](https://issues.redhat.com//browse/CMP-2633)
Related-Issue: [OSPCIX-338](https://issues.redhat.com//browse/OSPCIX-338)

Fix golang 1.22 symbols check

---

dist/releases/4.12/config.toml

Dockerfile: https://github.com/openshift/operator-framework-olm/blob/release-4.12/operator-lifecycle-manager.Dockerfile
Failed nightly [run](https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-ci-openshift-release-master-nightly-4.12-fips-payload-scan/1804169324097703936)
Coping over from from 4.13 exclude

exclude operator-lifecycle-manager-container

---

config.toml

We are building a rhel8-based image that includes both rhel8 and rhel9 cni binary and copies the correct one to the node at runtime. See https://issues.redhat.com/browse/OSSM-6411 for details

[OSSM-6411] Ignore rhel9 binary in rhel8 istio-cni image

---

internal/validations/validations.go

Golang version 1.22 does not have hardcoded libcrypto versions anymore, and does not emit the libcrypto version in the binary output of a go binary (e.g., using strings).
Because of this, the approach we were using to detect the OpenSSL version based on a regular expression and attempting to match that with the binary output does not work for binaries built with golang 1.22.
This is particularly prevalent with OpenShift 4.17 payloads that are using RHEL 9 and golang 1.22 base images.
This commit updates the binary scan logic to skip checking binaries for OpenSSL versions when using golang 1.22.

CMP-2639: Exclude binary libcrypto check using golang 1.22

---

config.toml

runc does not use any cryptography, and since runc init is executed in the context of a container, trying to load openssl breaks it, so we compile runc with no_openssl tag (see OCPBUGS-36541).
Add an appropriate exclusion for runc.

config: exclude runc

---

dist/releases/4.16/config.toml

Dockerfile: https://github.com/openshift/operator-framework-olm/blob/release-4.16/operator-framework-tools.Dockerfile
Error log: https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-ci-openshift-release-master-nightly-4.16-fips-payload-scan/1816057374515924992

add ose-operator-framework-tools-container to 4.16 exclude

---

dist/releases/4.14/config.toml
dist/releases/4.15/config.toml

https://github.com/openshift/machine-config-operator/pull/4476 was needed for Hypershift to use rhel9 binaries to generate config for 4.14/4.15, so ignore them like the daemon for the dual build.
This shouldn't affect any other versions.

MCO: ignore additional binaries for 4.14/4.15

---

config.toml

The change to not link against openssl was backported to 4.16-4.12
as part of OCPBUGS-36541 but seems to manifest with different error
there than in 4.17 due to differences in golang versions.

OCPBUGS-37846: rpm.runc ignore ErrLibcryptoMissing

---

dist/releases/4.17/config.toml
dist/releases/4.18/config.toml

Follows https://github.com/openshift/check-payload/pull/213
Dockerfile: https://github.com/openshift/ocp-release-operator-sdk/blob/release-4.17/release/sdk/Dockerfile
In the initial Slack [thread](https://redhat-internal.slack.com/archives/CB95J6R4N/p1723054496104479) we only saw failures in 4.13-4.15, but now it seems to be failing in 4.17 and 4.18 as well. 
No issues reported in 4.16 though, not sure why.

openshift-enterprise-operator-sdk-container update exclude

---

dist/releases/4.16/config.toml

RHEL 9.2 and 9.4 share openssl fips providers and thus should be equivalent

Add RHEL 9.4 to certified distributions

---

internal/validations/validations.go

Changed from `openssl-fips` to `openssl` in 
https://github.com/golang-fips/go/commit/1a6ccca3dfbb775968f7355de81d1e615b6f334f#diff-36aa6419af2cb44101da524e8049e031f55f5733b7867a0bee642e0173794269L34

Update checks to support golang 1.21.13 symbols

---

dist/releases/4.17/config.toml

These containers aren't built with CGO enabled, but they're not used as
part of the MCE operator. They're just shipped with the operator as a
convenience so QE can extract them and use them for testing.

CMP-2853: Exclude QE convenience containers

---

internal/rpm/rpm.go

When performing a local scan, a relative path can be provided, and rpm fails like this:
rpm -qf error: exit status 1 (stderr=rpm: arguments to --root (-r) must begin with a /)
Use an absolute path.

int/rpm: use abs path for rpm --root

---

config.toml
dist/releases/4.15/config.toml
internal/validations/validations.go

The symbol import changed in go 1.20.12 from:
`vendor/github.com/golang-fips/**openssl-fips**/openssl._Cfunc__goboringcrypto_DLOPEN_OPENSSL` to `vendor/github.com/golang-fips/**openssl**/openssl._Cfunc__goboringcrypto_DLOPEN_OPENSSL`

fixes for check-payload for 4.15

---

config.toml

Add RHACS client binaries (downloaded from the running service by users; not executed within the fips cluster) to base exclusion from fips scanning.
RHACS and these binaries are not ocp-version specific.

ignore rhacs client binaries

---

dist/releases/4.13/config.toml
dist/releases/4.18/config.toml

[[payload.virt-handler-rhel9-container.ignore]]
error = "ErrNotDynLinked"
files = ["/usr/bin/container-disk"]
[[payload.virt-launcher-rhel9-container.ignore]]
error = "ErrNotDynLinked"
files = ["/usr/bin/container-disk"]
[[payload.virt-cdi-importer-rhel9-container.ignore]]
error = "ErrGoNotCgoEnabled"
files = [
"/usr/bin/cdi-containerimage-server"
]
[[payload.kubevirt-tekton-tasks-copy-template-rhel9-container.ignore]]
error = "ErrGoNotCgoEnabled"
files = [
"/usr/bin/kubevirt-tekton-tasks.test"
]
[[payload.kubevirt-ssp-operator-container.ignore]]
error = "ErrGoNotCgoEnabled"
files = [
"/usr/bin/ssp-operator.test"
]
[[payload.kubevirt-tekton-tasks-copy-template-container.ignore]]
error = "ErrGoNotCgoEnabled"
files = [
"/usr/bin/kubevirt-tekton-tasks.test"
] …

Cnv fips separate the package files to pass the scan

---

dist/releases/4.13/config.toml
dist/releases/4.18/config.toml
dist/releases/4.19/config.toml

as we move to v4.19 update the config for 4.19 and added missing:
```
[[payload.virt-handler-rhel9-container.ignore]]
error = "ErrNotDynLinked"
files = ["/usr/bin/container-disk"]
```

added to v4.19 and virt-handler ignore

---

dist/releases/4.16/config.toml
dist/releases/4.17/config.toml
dist/releases/4.18/config.toml
dist/releases/4.19/config.toml

Fips scanner reports
```
Images with failures: ===================== image: registry.redhat.io/openshift-service-mesh/kiali-rhel9-operator@sha256:25a12f12294834a58f26792989432ca246cde43eb055ccda74c8a5c8af119ebe build: openshift-istio-kiali-operator-container-2.4.1-1 check-payload failures: * /usr/libexec/catatonit/catatonit: executable is not dynamically linked
```
for our kiali operator image. 
We use `ose-ansible-rhel9-operator:v4.17.0-202412170235` as a base image for which it was resolved by https://github.com/openshift/check-payload/pull/223 .
I have added kiali operator to ignore list as well.

[OSSM-8688] Ignore catatonit for kiali operator

---

internal/validations/validations.go

The check for go tags was not being executed.
Resolves https://github.com/openshift/check-payload/issues/229

execute gotags/goexperiment checking

---

dist/releases/4.14/config.toml
dist/releases/4.15/config.toml
dist/releases/4.16/config.toml
dist/releases/4.17/config.toml

I made last PR https://github.com/openshift/check-payload/pull/248 based on the result of the FIPS check on CVP. However, CVP was using for versions v4.14 and up the 4.19 configuration file. On konflux this is not like this anymore, konflux uses the respective version (for example v4.14 uses the 4.14 configuration file). A couple of ignores were missing because of that. I just replicated them on the missing versions.

Add virt-handler and virt-launcher ignores that weren't reported by CVP

---

internal/types/types_config.go
main.go

- Turn off usage output on scan failures
- Prefer `Run()` when no errors are returned
- Put config output behind verbosity flag

Turn off usage on scan failures

---

dist/releases/4.20/config.toml

As part of OCP branching step for OCP 4.20
the [4.19 config file](https://github.com/openshift/check-payload/blob/main/dist/releases/4.19/config.toml)
was copied.
No changes were added

ART-12531: create 4.20 config file

---

dist/releases/4.19/config.toml
dist/releases/4.20/config.toml

More information -> https://issues.redhat.com/browse/KFLUXSPRT-3109 and https://redhat-internal.slack.com/archives/C04PZ7H0VA8/p1747042738939379
It seems the tool is having a false positive with our ocp-virt-validation-checkup binary. Even if we are building it using the correct settings and the binary has C dependencies...
```
ENV GOEXPERIMENT strictfipsruntime
ENV GOFLAGS "-tags=strictfipsruntime"
RUN GOARCH=${TARGETARCH} GOOS=linux CGO_ENABLED=1 go test -c -o bin/kv.test ./tests
```
```
bash-5.1# ldd test/kv.test 
linux-vdso.so.1 (0x00007fc004462000)
libresolv.so.2 => /lib64/libresolv.so.2 (0x00007fc004446000)
libc.so.6 => /lib64/libc.so.6 (0x00007fc00423e000)
/lib64/ld-linux-x86-64.so.2 (0x00007fc004464000)
bash-5.1# ldd test/ssp.test 
linux-vdso.so.1 (0x00007f0ea4845000) …
```

Add CGO_ENABLED as an exclusion for ocp-virt-validation-checkup due to false positive

---

config.toml

- mta-cli can't have CGO_ENABLED set
- catatonit needs to be ignored

Ignore CLI and catatonit for MTA

---

dist/releases/4.19/config.toml
dist/releases/4.20/config.toml

Follow up of https://github.com/openshift/check-payload/pull/265
The binary path and name changed, so we are requesting to update the exception to the new name and path. Nothing else changed.

Update OCP virt validation exception binary path

---

dist/releases/4.14/config.toml

- Back-porting exception that was only done from ocp 4.15 and up since that was the oldest CVP would use when running check-payload
- Now that we are building File-based catalogs for OCP versions in konflux, it appears the check-payload is run using the OCP 4.14 config for the ocp 4.14 FBC and so we get the failure again for `diskrsync`.
- Previous PR for reference: https://github.com/openshift/check-payload/pull/177

volsync-container exception for diskrsync binary (for ocp 4.14)

---

dist/releases/4.16/config.toml

Adds RHEL 9.6 to the list of certified distributions for OCP 4.16.
Related issue: https://github.com/openshift/check-payload/issues/272
Note this does not resolve everything in the above issue, but will unblock failing scans on OCP 4.16 that use a RHEL 9.6 base image.
Remaining questions/problems from the above issue:
- Why does only OCP 4.16 have this list of certified distributions in the config.toml?
- Why do many images built with the same RHEL 9.6 base image pass the scan without this fix?

add RHEL 9.6 to certified_distributions for OCP 4.16
