validations.go

We can't skip reading the symtable because it is used to set baton.GoNoCrypto which is later used by other checks.
This reverts #34 (commit 944e49c7b61c782419c6a7254602acd1d94e66de).

Revert "perf: validateGoSymbols: skip early"

---

podman.go
scan.go
types.go

Add support for skipping bundle images.

add support for skipping bundle images

---

internal/golang/elf.go
internal/golang/elf_go120.go
internal/golang/goscan.go
internal/podman/podman.go
internal/scan/node_scan.go
internal/scan/printer.go
internal/scan/scan.go
internal/types/types.go
internal/types/types_config.go
internal/types/types_scan_result.go
internal/types/types_scan_results.go
internal/validations/validations.go
internal/validations/validations_openssl.go
internal/validations/validations_test.go
main.go

Refactor to a golang layout. No other changes.

refactor to golang layout

---

internal/scan/printer.go

Fixes the output on a successful run.

OCPBUGS-15916: fix output on runs

---

internal/scan/printer.go

Since all its users only need that string.

Make getComponent return string

---

internal/validations/validations.go

A few optimizations mostly aimed to reduce LOC (but also reducing the amount of garbage to collect).

Minor optimizations

---

dist/releases/4.10/config.toml
dist/releases/4.11/config.toml
dist/releases/4.12/config.toml
dist/releases/4.13/config.toml

chore: [CRW-4582](https://issues.redhat.com//browse/CRW-4582) add more exceptions for known issues
Signed-off-by: Nick Boldt <nboldt@redhat.com>

chore: CRW-4582 add more exceptions for known issues

---

internal/scan/node_scan.go
internal/scan/scan.go
internal/types/types_scan_result.go

Minor logging improvements.
Please see individual commits for details.

feat: show component, tag, rpm in logs

---

Makefile
dist/releases/4.10/config.toml
dist/releases/4.13/config.toml
dist/releases/4.9/config.toml
internal/types/error_map.go
internal/types/types.go

1. Fix some known error names and the CI check for these.
2. Fix merging configs with the same key.

Hotfix: fix error names, configs merging

---

CHANGELOG.md
config.toml
dist/releases/4.12/config.toml
dist/releases/4.13/config.toml
dist/releases/4.14/config.toml
internal/types/types_config_file.go

Please see individual commits for details. Split for ease of review.

Add more validation to config; unify some entries; add 4.14 config

---

CHANGELOG.md

chore(release): prep for 0.3.1 release

---

Dockerfile

Integrate podman in the image so that we can run the check in a container ( in Prow CI ).

Add podman so that we can run the check in the container

---

internal/podman/podman.go

Sometimes quay.io returns HTTP 500 error. To improve resilience of the tool when using it from scripts, let's retry once if we see this.
Fixes https://issues.redhat.com/browse/OCPNODE-1875

internal/podman: add retry

---

Dockerfile

dockerfile: bump base to rhel 9

---

README.md

Add missing `\` to command example

README minor fix

---

Dockerfile
internal/golang/goscan.go

This PR adds functionality for s390x scans.

fallback to bigendian to check for golang magic number

---

OWNERS

add Lance Bragstad to owners

---

dist/releases/4.17/config.toml

Copying over from 4.16 `config.toml`

Setup 4.17 config.toml

---

dist/releases/4.17/config.toml

Same as https://github.com/openshift/check-payload/pull/186, but for 4.17 config

add rukpak and lifecycle manager to 4.17

---

dist/releases/4.13/config.toml
dist/releases/4.14/config.toml
dist/releases/4.15/config.toml

Follows https://github.com/openshift/check-payload/pull/188
Update 4.15, 4.14, 4.16 lifecycle manager exclude and 4.15, 4.14 rukpak exclude

update rukpak and lifecycle manager excludes

---

internal/validations/validations.go

Golang 1.22 symbols have changed, resulting in false negative results on
4.17 payloads using golang 1.22.
This commit updates the symbols check to account for this change.

CMP-2633: Update check to support golang 1.22 symbols

---

internal/scan/scan.go
main.go

Previously, we weren't passing in the `OpenshiftComponent` to the local
scan check. This meant that when you ran a local scan against the file
system of a container mounted locally, check-payload wouldn't honor the
exclusions implemented in the global configuration or the versioned
configuration files available in the check-payload binary.
This commit updates the scan local command to pass this information in,
and ports the component string argument to an `OpenshiftComponent`
struct, allowing us to reuse the existing exclusions. Ultimately making
it so `scan local` and `scan payload` behave similarly.
Fixes #193

Pass component information to scan local check

---

dist/releases/4.18/config.toml

Copying over from https://github.com/openshift/check-payload/blob/main/dist/releases/4.17/config.toml
No changes were added

add 4.18 config.toml

---

dist/releases/4.13/config.toml
dist/releases/4.14/config.toml
dist/releases/4.15/config.toml

ref slack [thread](https://redhat-internal.slack.com/archives/CB95J6R4N/p1723054496104479)

openshift-enterprise-operator-sdk-container update exclude

---

dist/releases/4.19/config.toml

As part of OCP branching step. Copied the [4.18 config file](https://github.com/openshift/check-payload/blob/main/dist/releases/4.18/config.toml)
No changes were added

create 4.19 config file

---

dist/releases/4.14/config.toml

add skip for sriov cni in 4.14

---

Dockerfile.upstream

- Realignment with `Dockerfile`
- Add missing `wget`

Fix `Dockerfile.upstream`
